- hosts: front
  remote_user: root
  vars_files:
    - ../secrets.yml
  vars:
    github_repo_url: https://{{github_user}}:{{github_token}}@gitlab.com/Esceve/cryptotek.git
    # working_directory: /root/test-front/
    working_directory: /root/dist/front
    web_dns: front.retrogala.ovh
  tasks:
    - name: "Pull new changes from gitlab retrogala"
      git:
        repo: "{{github_repo_url}}"
        dest: "{{working_directory}}"
        version: master
        accept_hostkey: yes
      register: repo

    - name: "remove the old packages"
      file:
        path: "{{working_directory}}node_modules"
        state: absent
      when: repo.changed

    - name: "install new packages"
      npm:
        path: "{{working_directory}}"
      when: repo.changed

    # - name: "build the new project"
    #   shell: "/bin/bash install.sh"
    #   args:
    #     chdir: "{{working_directory}}"
    #   when: repo.changed
    # - name: "clean and copy new project"
    #   # become: yes
    #   shell: |
    #     rm -rf /var/www/{{web_dns}}/html/*
    #     cp -r {{working_directory}}/dist/front/* /var/www/{{web_dns}}/html/
    #   when: repo.changed
    - name: "clean and copy new project"
      # become: yes
      shell: |
        rm -rf /var/www/{{web_dns}}/html/*
      # when: repo.changed

    - name: example copying file with owner and permissions
      copy:
        src: ../dist/front/
        dest: /var/www/{{web_dns}}/html/
        owner: root
        group: root
        mode: 0644

    - name: "restart http service"
      # become: yes
      shell: "systemctl restart nginx"
      # when: repo.changed
